LifeOverFlow/LifeOverFlow/config/routes.rb
LifeOverFlow::Application.routes.draw do

  root :to => 'questions#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :questions do
    resources :answers
  end

resources :questions, :comments, :answers do
  resources :votes
end

  resources :comments
  resources :users
  resources :sessions
end

LifeOverFlow/LifeOverFlow/app/models/ comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment_content
  belongs_to :commentable, :polymorphic => true
  belongs_to :question
end

LifeOverFlow/LifeOverFlow/app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :answer_content, :user_id

  validates :answer_content, presence: true
  belongs_to :user
  belongs_to :question
  has_many :comments, :as => :commentable
end

LifeOverFlow/LifeOverFlow/app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment_content, :commentable_id, :commentable_type, :user_id
  belongs_to :user
  belongs_to :commentable, :polymorphic => true
end

LifeOverFlow/LifeOverFlow/app/models/question.rb
require 'date'

class Question < ActiveRecord::Base
  attr_accessible :question_content, :question_title, :user_id

  validates :question_content, presence: true
  validates :question_title, presence: true
  belongs_to :user
  has_many :comments, :as => :commentable
  has_many :answers
  has_many :votes, :as => :voteable

  def votes_total
    total_up_votes = self.votes.find_all_by_vote_type('up').count
    total_down_votes = self.votes.find_all_by_vote_type('down').count
    votes_total = total_up_votes - total_down_votes
  end
end

LifeOverFlow/LifeOverFlow/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :email, :password

  attr_accessor :password
  before_save :encrypt_password
  validates_presence_of :username
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :questions
  has_many :answers
  has_many :comments

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

LifeOverFlow/LifeOverFlow/app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :vote_type, :voteable_id, :voteable_type

  belongs_to :user
  belongs_to :voteable, :polymorphic => true

end

LifeOverFlow/LifeOverFlow/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
before_filter :require_login, only: [:new, :create]

  def create
    @user = current_user
    @question = Question.find params[:question_id]
    @answer = @question.answers.build params[:answer]
    @answer.update_attributes(:user_id => @user.id)
    if @answer.save
      render :partial => 'answer', :locals => {answer: @answer}
    else
      render :nothing => true
    end
  end

  def require_login
    puts current_user
    unless current_user
      flash[:error] = "You must be logged in to create a question"
      redirect_to root_path
    end
  end

end

LifeOverFlow/LifeOverFlow/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

LifeOverFlow/LifeOverFlow/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(params[:comment])
    @user = current_user
    @comment.update_attributes(:user_id => @user.id)

    if @comment.commentable_type == "Question"
      if @comment.save
        render :partial => 'comment_on_question', :locals => {:comment => @comment}
      else
        render :new
      end
    else
      if @comment.save
        render :partial => 'comment_on_answer', :locals => {:comment => @comment}
      else
        render :new
      end
    end
  end

end

LifeOverFlow/LifeOverFlow/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
before_filter :require_login, only: [:new, :create]

  def index
    @questions = Question.all
    @question = Question.new
    @answer = Answer.new
    if params[:recent]
      @questions = Question.order(:created_at)
      render :partial => 'questions', :locals => {:questions => @questions}
    end
    if params[:upVotes]
        @questions = @questions.sort {|q1,q2| q2.votes_total <=> q1.votes_total}
        render :partial => 'questions', :locals => {:questions => @questions}
    end
  end

  def show
    @question = Question.find params[:id]
    @comment = Comment.new
    @answer = Answer.new
  end

  def new
    @question = Question.new
    @answer = Answer.new
  end

  def create
    @question = Question.new params[:question]

    @user = current_user
    @question.update_attributes(:user_id => @user.id)

    if @question.save
      render :partial => 'question', :locals => {:question => @question}
    else
      render :text => @question.errors.full_messages.join(', '), :status => :failure
    end
  end

  def destroy
    question = Question.find params[:id]
    question.destroy
    redirect_to root_path
  end


  def require_login
    puts current_user
    unless current_user
      flash[:error] = "You must be logged in to create a question"
      redirect_to root_path
    end
  end

end

LifeOverFlow/LifeOverFlow/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

LifeOverFlow/LifeOverFlow/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
    @user_questions = @user.questions
    @user_answers = @user.answers
    @user_comments = @user.comments
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user]

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

end

LifeOverFlow/LifeOverFlow/app/controllers/votes_controller.rb
class VotesController < ApplicationController



def create
  vote_params = {vote_type: params[:vote_type], voteable_type: params[:voteable_type], voteable_id: params[:voteable_id] }
  @vote = Vote.new(vote_params)
  if @vote.save
    question = Question.find(@vote.voteable_id)
    @vote_total = question.votes_total
    @vote_total
    render json: @vote_total.to_json
  else
    @errors = @vote.errors.full_messages
  end
end

end

LifeOverFlow/LifeOverFlow/app/helpers/application_helper.rb
module ApplicationHelper

end

LifeOverFlow/LifeOverFlow/app/views/answers/_answer.html.erb
<div id="answer_content">
  <%= answer.answer_content %>
</div>

LifeOverFlow/LifeOverFlow/app/views/answers/new.html.erb
<div id="create-answer">
<h1> Create an Answer Below </h1>
  <%= form_for [@question, @answer] do |f| %>
    <p><%= f.label :answer_content %>&nbsp;<%= f.text_field :answer_content %></p>
    <p><%= f.submit "Submit" %></p>
  <% end %>
</div>

LifeOverFlow/LifeOverFlow/app/views/comments/_comment_on_answer.html.erb
<div class="comment">
  <div class= "answer_comment">
    <%= "#{comment.comment_content}" %>
  </div>
</div>

LifeOverFlow/LifeOverFlow/app/views/comments/_comment_on_question.html.erb
<div class="comment">
  <div class= "comment_content">
    <%= "#{comment.comment_content}" %>
  </div>
</div>

LifeOverFlow/LifeOverFlow/app/views/layouts/_footer.html.erb
<span id="footer"><a href="#">Click me!</a></span>

LifeOverFlow/LifeOverFlow/app/views/layouts/_header.html.erb
<div class="header">
  <img src = "http://images.wikia.com/uncyclopedia/images/archive/8/80/20070603184500!Smiley.png">
  <div id="user_nav">

  <ul class="nav nav-pills nav-stacked">
    <% if current_user %>
      <li id="user_btn"> <%= link_to "#{current_user.username}", user_path(current_user.id) %></li>
      <li> <%= button_to "Log out", log_out_path, :class => "btn btn-danger", :method => :get %></li>
    <% else %>
      <li> <%= button_to "Sign Up", sign_up_path, :class => "btn btn-success", :method => :get %></li>
      <li><%= link_to "Log In", log_in_path %></li>
    <% end %>
  </ul>
  </div>

  <div id="main_logo">
    <a href='/'>Life Overflow</a>
  </div>




</div>

LifeOverFlow/LifeOverFlow/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LifeOverFlow</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>


  <!-- BOOSTRAP -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

</head>
<body>

  <%= render partial: 'layouts/header' %>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<hr id = "horizontal">

<div class="main_container">
  <%= yield %>
</div>

</body>
</html>

LifeOverFlow/LifeOverFlow/app/views/questions/_question.html.erb
<div class="question">
  <div class= "votes_container">
      <div class = "vote_count">
        <%= question.votes_total %>
      </div>
      <div class="vote_booth">
      <%= link_to 'UP', question_votes_path(question, vote_type: "up", voteable_type: "Question", voteable_id: question.id), remote: true, method: :post, class: "vote" %>
      <%= link_to 'DOWN', question_votes_path(question, vote_type: "down", voteable_type: "Question",voteable_id: question.id), remote: true, method: :post, class: "vote"  %>
    </div>
  </div>
  <div class = "question-content">

    <span class = "question_title"><h3><%= "#{question.question_title}" %></h3></span>

    <div class="question_buttons">
        <span class ="q_btn"><%= link_to 'Show' , question_path(question) %></span>
        <span>Created on: <%= "#{question.updated_at}" %></span>
        <span>Created by: <%= link_to "#{question.user.username}", user_path(question.user.id) %></span>
    </div>
  </div>
</div>

LifeOverFlow/LifeOverFlow/app/views/questions/_questions.html.erb
<% @questions.each do |question| %>
          <div class="question">
        <div class= "votes_container">
            <div class = "vote_count">
              <%= question.votes_total %>
            </div>
            <div class="vote_booth">
            <%= link_to 'UP', question_votes_path(question, vote_type: "up", voteable_type: "Question", voteable_id: question.id), remote: true, method: :post, class: "vote" %>
            <%= link_to 'DOWN', question_votes_path(question, vote_type: "down", voteable_type: "Question",voteable_id: question.id), remote: true, method: :post, class: "vote"  %>
          </div>
        </div>
        <div class = "question-content">

          <span class = "question_title"><h3><%= "#{question.question_title}" %></h3></span>

          <div class="question_buttons">
              <span class ="q_btn"><%= link_to 'Show' , question_path(question) %></span>
              <span class "question_timestamp"><%= "#{question.updated_at}" %></span>
              <span>Created by: <%= link_to "#{question.user.username}", user_path(question.user.id) %></span>
          </div>
        </div>
      </div>
  <% end %>

LifeOverFlow/LifeOverFlow/app/views/questions/index.html.erb
<div class="text-center">
    <em>Order by:</em>
    <div class="btn-group">
      <span id="upVotes"><%= link_to "UpVotes",{:controller => "questions" , :action => "index", :upVotes => true }, :remote => true %></span><br>
      <span id="recent"><%= link_to "Most Recent", {:controller => "questions" , :action => "index", :recent => true }, :remote => true  %></span>
    </div>
  </div>


<div id="show_questions">
  <h2>All questions:</h2><br>
  <% @questions.each do |question| %>
    <%= render 'questions/question', :question => question %>
  <% end %>
</div>

<% if current_user %>
  <%=link_to "Create a Question", "#", :class => 'new_question' %>
<% end  %>
<div id="quest_errors">

</div>

<%= form_for @question, :remote => true, :html => {:class => 'questionform' } do |f| %>

  <%= f.text_field :question_title, size: "98", placeholder: "Title" %>
  <br>
    <%= f.text_area :question_content, size: "100x12", placeholder: "Content" %>
  <%= f.submit %>
<% end %>

LifeOverFlow/LifeOverFlow/app/views/questions/new.html.erb
<h1> Create a Question Below </h1>

<%= form_for @question do |f| %>
  <p><%= f.text_field :question_title, size: "98", placeholder: "Title" %></p>
  <p><%= f.text_area :question_content, size: "100x12", placeholder: "Content" %></p>
  <p><%= f.submit %></p>

<% end %>

LifeOverFlow/LifeOverFlow/app/views/questions/show.html.erb
<div id="show_question">
  <h2><%= @question.question_title %></h2>
  <p><%= @question.question_content %></p>
</div>

<div class="question-comments">
  <div id="show_question_comments">
    <% @question.comments.each do |comment| %>
      <div class="comment"><%= comment.comment_content %> - <%= link_to "#{comment.user.username}", user_path(comment.user.id) %></div>
    <% end %>
  </div>
  <%= link_to "Comment on This Question", "#", :class => 'new_comment_on_question' %>
  <div id="comment_question_errors">

<%= form_for @comment, :remote => true, :html => {:class => 'questionCommentForm'} do |f| %>
    <%= f.label :comment_content %>
    <%= f.text_field :comment_content %>
    <br>
    <%= f.hidden_field :commentable_id, value: @question.id%>
    <%= f.hidden_field :commentable_type, value: "Question" %>
    <%= f.submit "Add Comment" %>
<% end %>
  <br>
</div>

<% if current_user %>
  <%= link_to 'New Answer', '#', :class =>'new-answer'  %>

  <div id="answer-question">
    <%= form_for [@question, @answer], remote: true, :html => {:class => 'hidden'} do |f| %>
    <%= f.label :answer_content %>
    <%= f.text_field :answer_content %>
    <%= f.submit "Submit" %>
    <% end %>
 </div>

<% end  %><br>


<div id="all_answers">
  <h4><%= @question.answers.count %> Answers</h4>
  <% @question.answers.each do |answer| %>
    <div class="show_answer">
      <div id = "answer_content">

        <%= answer.answer_content %> - <%= link_to "#{answer.user.username}", user_path(answer.user.id) %>
      </div>
      <%= link_to "Comment on Answer", '#', :class => 'new_comment_on_answer' %>
      <%= form_for @comment, :remote => true, :html => {:class => 'answerCommentForm'} do |f| %>
            <%= f.label :comment_content %>
            <%= f.text_field :comment_content %>
            <br>
            <%= f.hidden_field :commentable_id, value: answer.id%>
            <%= f.hidden_field :commentable_type, value: "Answer" %>
            <%= f.submit "Add Comment" %>
      <% end %>
      <div id="show_answer_comments">

      <div class="answer_comments">
         <% answer.comments.each do |comment| %>
          <div class="answer_comment"><%= comment.comment_content %> - <%= link_to "#{comment.user.username}", user_path(comment.user.id) %></div>
         <% end %>
      </div><br><br><br>

    </div>
  <% end %>
</div>

LifeOverFlow/LifeOverFlow/app/views/users/_form.html.erb
<div id="signup_form">

<%= form_for @user do |f| %>
  <div class="sign_up_fields">
    <p><%= f.text_field :username, placeholder: "User name" %></p>
    <p><%= f.text_field :email, placeholder: "Email address" %></p>
    <p><%= f.password_field :password, placeholder: "Password" %></p>
    <%= f.submit "Create Account"%>
  </div>
  <div class="error_messages">
    <% if @user.errors.any? %>
      <h2>Form is invalid</h2>
      <% for message in @user.errors.full_messages %>
        <%= message %>
      <% end %>
    <% end %>
  </div>
<% end %>
</div>

LifeOverFlow/LifeOverFlow/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render partial: 'users/form' %>

LifeOverFlow/LifeOverFlow/app/views/users/show.html.erb
<div class="show_user">
  <h1>Welcome to <%= @user.username %>'s Page!</h1>

  <h3>Questions You Have Created:</h3>

  <% @user_questions.each_with_index do |question, index| %>
    <div class="question">
      <div class = "question_title">
        <h4><%= "#{index+1}: #{question.question_title}" %></h4>
      </div>
      <div class="question_buttons">
        <span class ="q_btn"><%= link_to 'Show' , question_path(question) %></span>
        <span><%= link_to 'Delete' , question_path(question), :method => :delete %></span>
      </div>
    </div>
  <% end %>

  <h3>Answers You Have Created:</h3>
  <% @user_answers.each_with_index do |answer, index| %>
    <div class="question">
      <div class = "question_title">
        <h4><%= "#{index+1}: #{answer.answer_content}" %></h4>
      </div>
      <div class="question_buttons">
         <div class = "question_button">
          <%= link_to 'Show Original Question' , question_path(answer.question.id) %>
        </div>
      </div>
    </div>
  <% end %>

  <h3>Comments You Have Created:</h3>

  <% @user_comments.each_with_index do |comment, index| %>
    <div class="question">
      <div class = "question_title">
        <h4><%= "#{index+1}: #{comment.comment_content}" %></h4>
      </div>

        <div class="question_buttons">
           <div class = "question_button">
            <% if comment.commentable_type == "Question" %>
              <%= link_to 'Show Original Question' , question_path(comment.commentable.id) %>
            <% else %>
              <%= link_to 'Show Original Question' , question_path(comment.commentable.question_id) %>
            <% end %>
          </div>
        </div>
    </div>
  <% end %>
</div>